# Generated by Django 5.2.5 on 2025-09-11 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Paymagics_Admin', '0001_initial'),
        ('Paymagics_Payor', '0001_initial'),
        ('Paymagics_PayorStaff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Paymagics_PayorStaff.paymenttemplate'),
        ),
        migrations.AddField(
            model_name='payee',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='payees', to='Paymagics_Payor.category'),
        ),
        migrations.AddField(
            model_name='payee',
            name='payor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Paymagics_Admin.userprofile'),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='payees',
            field=models.ManyToManyField(blank=True, related_name='excel_files', to='Paymagics_Payor.payee'),
        ),
        migrations.AddField(
            model_name='referralinvite',
            name='payor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='Paymagics_Admin.userprofile'),
        ),
    ]
