# Generated by Django 5.2.5 on 2025-09-11 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paymagics_Payor', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelFile',
        ),
    ]
