# Generated by Django 5.2.5 on 2025-10-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paymagics_Payor', '0003_delete_excelfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='iban',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payee',
            name='payee_type',
            field=models.CharField(choices=[('DOMESTIC', 'Domestic'), ('INTERNATIONAL', 'International')], default='DOMESTIC', max_length=20),
        ),
        migrations.AddField(
            model_name='payee',
            name='sort_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payee',
            name='swift_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
