# Generated by Django 5.2.5 on 2025-09-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paymagics_PayorStaff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttemplate',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttemplate',
            name='template_type',
            field=models.CharField(choices=[('payee', 'Payee Template'), ('payment', 'Payment Template')], default='payment', max_length=20),
        ),
    ]
