# Generated by Django 5.2.5 on 2025-09-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paymagics_PayorStaff', '0002_paymenttemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatepayee',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
