# Generated by Django 5.2.5 on 2025-09-12 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paymagics_PayorStaff', '0003_templatepayee_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatepayee',
            old_name='options',
            new_name='options_data',
        ),
    ]
